# Generated by Django 3.0.4 on 2020-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='course_type',
            field=models.CharField(choices=[('C', 'CDC'), ('E', 'Elective')], default='C', max_length=1),
            preserve_default=False,
        ),
    ]
