# Generated by Django 3.0.4 on 2020-04-16 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='merge_with',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='course_load.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
