# Generated by Django 3.0.4 on 2020-04-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0002_auto_20200416_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='course_load.Instructor'),
        ),
    ]
