# Generated by Django 3.0.4 on 2020-03-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0003_courseaccessrequested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseaccessrequested',
            name='course_type',
        ),
    ]
