# Generated by Django 3.0.4 on 2020-04-17 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0003_auto_20200417_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='merge_with',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='course_load.Course'),
        ),
    ]
