# Generated by Django 3.0.4 on 2020-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0004_remove_courseaccessrequested_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstructor',
            name='course_type',
        ),
        migrations.AddField(
            model_name='course',
            name='l_section_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='p_section_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='t_section_count',
            field=models.IntegerField(default=0),
        ),
    ]
