# Generated by Django 3.0.4 on 2020-04-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0007_auto_20200330_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_strength',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student_count',
        ),
        migrations.AddField(
            model_name='course',
            name='strength_per_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='strength_per_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='strength_per_t',
            field=models.IntegerField(default=0),
        ),
    ]
