# Generated by Django 3.0.4 on 2020-04-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0008_auto_20200402_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='strength_per_l',
            new_name='max_strength_per_l',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='strength_per_p',
            new_name='max_strength_per_p',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='strength_per_t',
            new_name='max_strength_per_t',
        ),
    ]
