# Generated by Django 3.0.4 on 2020-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0009_auto_20200402_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='section_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
