# Generated by Django 3.0.4 on 2020-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0010_courseinstructor_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comcode',
            field=models.IntegerField(default=0),
        ),
    ]
