# Generated by Django 3.0.4 on 2020-04-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0012_auto_20200406_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='l_section_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='p_section_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='t_section_count',
        ),
    ]
