# Generated by Django 3.0.4 on 2020-04-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0013_auto_20200406_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_data_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
